spring.application.name: rtddecrypter
logging:
  level:
    root: INFO
    org.apache.kafka: WARN

# OpenTelemetry
applicationinsights.enabled: '@applicationinsights.enabled@'
otel.log.level: ${OPENTELEMETRY_LOG_LEVEL:INFO}
otel.instrumentation.logback-appender.enabled: true # enable logback instrumentation
otel.traces.sampler.probability: 1.0 # sample probability for tracing (spans)
otel.metric.export.interval: 60000 # sampling rate for metrics (millis)
otel.exporter.otlp.enabled: false # disable send to OTLP endpoint

# Expose only health probes
management:
  metrics:
    export.defaults.enabled: false
    enable:
      all: false
      process.cpu: true
      system.cpu: true
      jvm.memory: true
      application: true
  endpoints:
    enabled-by-default: false
    web.exposure.include: health
  info.defaults.enabled: false
  endpoints.enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

decrypt:
  resources:
    base:
      path: src/test/resources
  private:
    key:
      base64: ${CSV_TRANSACTION_PRIVATE_KEY:LS0tLS1CRUdJTiBQR1AgUFJJVkFURSBLRVkgQkxPQ0stLS0tLQoKbFFJR0JHSWNzZ2dCQkFDNWJzdUFvZDM3UXBtdHY0MW1JR1JaUlgzNkNkYnFjN3JVOVp3MURyN2FLajZDS1VKQQpjZUlRZVNiZXR3NzVQc2RycENSUjZ2RmpxMjNRbnhIalJ6Q1Q2Z0p4Zm9MSEwxeFR3MklhOHZOVzlzUVRaR3owCjd1UUVDM0Nudk1sK3k3a3h2Rmk5bUFTa2VHMCtDaDg2YkgyTjN4eWN3VXpSMVRjVlpaVHBFN3RSSlFBUkFRQUIKL2djREFpT2VtN3ZhcUMzRzhEamlmdWJDdXNGUHdMTnNGYmhGcm1yTVF1QlExYnJNcW16cis2WmU3OTFJU2U5OAptYWpoZjByUW5rS0tQd1VGS05KZFdzSjlYbG9aWXMrQWFUSVNpYkpaZUJqeGk1NzRHYXFoTDh0Vy9kUDBpa3F0ClF2NTJnVFJWdEM1VkRmV09MdnJobVVyNVhrVEtkZ3MzNkl5QnkxZ0tMZTZwWVR6R2VVbHFHcjJ4cW96R1pxMWEKQk9rZ2prR05qc3JhbmxKbWNEbk4zMWFhQXphbGplUXR3U0I5Mm8vRTd5bTltU3pRSkwyQ3J1OVUvMlNvclBEdwpGeWdTTGIwUmxaN2RWTVhtNTZwZ2xDdGVXODQ3c3MzVmdXZGFoZFBHelJqQVVvZ2NoeTc1OG82K1lEbnc1T0VUCkYyZklVQlRLdzk2ZDY4cGhMcmo1N3ovTzFmblBsbW5LZjI1MUEzYm1zcUJFTzBMRENrR1lvT1dpL2JoSmlEbm0KVjYyb1crVWdkR3ZSeEtEbFVoVDBoY2o2Sk8xUWRiQ3JETFpXT05MTFBsU3U2b3doWXRhR1dPNG9PeE5DS0ZBMwpkMjJVMitCM3pjaEtneHROYzM5M0xNazRUNUkvTHhldzB6OU5KbytLNVF3QjRaNXY5akZiV0ZXMFAwZHBiM1poCmJtNXBJRTFoYm1OcGJta2dLRU5vYVdGMlpTQlVaWE4wSUZKVVJDa2dQR2RwYjNaaGJtNXBMbTFoYm1OcGJtbEEKY0dGbmIzQmhMbWwwUG9qU0JCTUJDQUE4RmlFRUVGbHRWbnhaZHlhTDg1S2prWTJDOWFSdTU4RUZBbUljc2dnQwpHd01GQ3drSUJ3SURJZ0lCQmhVS0NRZ0xBZ1FXQWdNQkFoNEhBaGVBQUFvSkVKR05ndldrYnVmQkE2Z0QvaXJVCjQ3SEtZKzVJSWpYQ1VrNEZHY2tCU3dIUUZBdHZQN1BtR3IyU1o4UlphU0dBOHJENWxkZFhaYVdZVEUrRFA1Zm4KUUEyWlQ5bkFENTRLanpQd3V3bDNmZTdScStrYmZGc0UzOWtlK2dnRWhnTjBGSzJ4S08xQ1QyL1k0MkpDckUxSQp0dGN6T2VtK0lvTlo0ampkQlJlYURNaG1ibFpqbFA3Z0JDSC9XWlY5blFJR0JHSWNzZ2dCQkFDM09hVEdER0FPCnlLNncyMTk2K2ZQSkRRSG8vY0VGZGhQNkhRNE5KT0VPd3hOdFpyWnUwd0tSM1dJRnZsVHViSUtQZHZVK3k3WE8KSnJUU3dQWWFyM1FTY0lQV2RKamw1OU1YYWdXL09QaTROMGFwMytVbUo4bU1NSUhyUHdaRG1uT0t1Yzl0UG9URQo5cDBRYTVLTk9DSlNvamljOE9rZDZaK0gzQlRYVXBUZm9RQVJBUUFCL2djREFzQ2J1MENWbmVHNDhDZzd2UlBzCmR5bkwrMUxWNmg0by9EUkFoUHhNL2VhSk9BNWlzUVZENG5zWGdqT1FaMzcwMGZrajBWUW1QR256eERDOUVzclAKS05ndjVpNkNWMDR4KzZLc285QlVtay8yWkxMdHpsTkdUMnVMbVEyU0pta3g2bE9mWStYblYxTGpQaEppMmNHZgo4KytjYmZMS0Ezcm83dnJqUW5hazFqMHkwSFAwVkhtNy9VK3h2UFBNVW5rU0VTZXN4Vy9WV0ord3FDdGEyRlBaCkg2cWVLUVRVRjlaSEVSL3hTOWVlQ0h5a0M4YndFUW5Jb0QvOVFUQSt3Y2VhMHNMdDhKbEVFUG10TTU3S2NEM1UKMEY5QjNOV3FkbGU2TXVielNTWGJCVUU1cndXejJxZ05YTGZ6ZzllMmVIV2xwRURPdWZBMlpIZ0tldEJIOExwSgp1RFVBVnRRT2Fucll5MXdldXkxQTdrQy9sbGhNRzlYVmJtTW9lTGJ6aUFWaFpudFJmKzdNL1pDZ2Z6bjdRSW9mCkxXRTllZTVLR1RQYjRoLy9qY3JVTkxzQ3loTkllYlVRL0hCaU9QSmNxN3dSb0puZ1R5cXVLUlV2OURFRGl5TU4Kenc5UVBta244RzlXeEl3TjlQeXA3cm5wUlgzMERIYUl0Z1FZQVFnQUlCWWhCQkJaYlZaOFdYY21pL09TbzVHTgpndldrYnVmQkJRSmlITElJQWhzTUFBb0pFSkdOZ3ZXa2J1ZkJuMFVFQUxGTGJ3SjR5dlFLNDJ6RWRYYXF4aTVCCm5oKzhaQVIvOG9uOFdhVnFZdUw4NDNjR01jUkRhRjR4emM5UVdwa2hMaUlMVFNnaWZLQ1JGSDl2T04xdVcvR2sKUlBPY2NOQjNydkt5NytpU2hoNmR3anZlSG05ZTdaNlMxaDdsVEsvQUxERUJnQWswSmM3VDJ6ZDR0bXVyaGJQeQo1MFNMOGtnZU9FQWNOc0wwMGx2eAo9OE1DbQotLS0tLUVORCBQR1AgUFJJVkFURSBLRVkgQkxPQ0stLS0tLQo=} # default value is just for testing purposes
      password: ${CSV_TRANSACTION_PRIVATE_KEY_PASS:privatekeypass}
  #      base64: ${LS0tLS1CRUdJTiBQR1AgUFJJVkFURSBLRVkgQkxPQ0stLS0tLQoKbFFkR0JHSU14ZTRCRUFERm5EeTFBU3MrVXpxT3Rxb2VLK2o1aXNscHB4ZXp0VnowMk9jWUY2cmFVL09xQkcwbgpWN2hJaGhGUm40bVp1dDh0RkZITWZyWnNtVlg0MElOSmh2K1U2Y0tPZUVVOU0wdHZMRDRuZmZzdGVwSlZnMG1XCmIzSGdIMmNZbEMwQ1hnbHNKMHVEYTlCTWxvalEyVmhiSC9Rcys3bUFOVHA5Yy9qbUhhbkdFSGRCTkdiU09SN20KdWFWcGJtV1VoejNvRGNHQTJuRkNEME9palNYUTVHZ2VTWWR2cTMybG1QVFlXbHY5cEdXK0NDMDN4ZWUyU0JhWgpSSXVGeEpOS00vdUpZMDZibHY5bk1KOWhiTmE3aWVLSlIvbDVnWmpnVVdVOUM5RUlxK3NTd21lVTVYMnVrVUd6CjhGbS9mRWVCbHdRYWM0SjF2TEtyUFpDN3JLUDh3eHVnQUVOdVkvWlpxcTQ1eDdQOUNlOGt3UXovdXduUlR1MkUKYnJsNmp3Q01tUElWMUJDZWg1N2lUd1RYdFBES0ttRkZpSTVINE9nUlZpMzNmek00dCtESk1RRnlaRzBMZXZ1TApnK0xkUUVad2JHU2JPOHZVTkRsQ2ZrM25HSEVkejdJUGZCdGJhVFBwVDJxMzRYbVFzS2lhRVJjUnV4TDZlUjMyCkhSNjB2TkErUkQ2ZmhTLytBbDBZQXJJdFMyRUhGZHh3MkJHaENNOStweWVKQms2aGxuNWF2V0NNbFptUyt0OVQKRmEzcmN2aVNiVWdRamhONlErVnBhSXZXbUFtbWNuNzN4czltMVRJZDA3ZFZzRkg5TjNVbFpQcndMRlJTVk03Sgo3U1dwTnlWbWZpZXdaZ0Q1SzFkRXdvc21nUUUrZEFLQitKMWkzQ20yd0FmTWZhRTZXZHNtUjlFbzV3QVJBUUFCCi9nY0RBcDVNaE9TTEJXVmw4NEVOem5DTVl1OWJwcjlCRFZzeTdvc1VMNmFjblo5UFh0R0s5aU9oOHljOFhHQ1EKbUsrdEtwNGttQTNza0FmLzdTTnVDeDRKakk3Z3kzSm1tOGpBWU5BU3RWejRwbmMvdHg0MmR3OHRZRFhKLzZzMQpwRFh5eGp6WkxYbGdkNmRNZmNGS0twankrTnkxK1pzR1BCdVNXcEFpZFFmcUxHVm9SY2VNVEpPV0U3M1ZFR05TClB6czV3RmlienJWRTIvV092a2VBK1lQYVpvM0dDdGFQR0JtWE1CWTdSc3c0bkUxRWZKTU5tQ09CWWJuYWE3a3QKUm1GNnl6TlRpZDQzODcwdVQwQmthOWV4K2oySXZVTUhHRGlRa05aNWU5N2x2Z1d6TmlGREdqNFQrY1VJTS8zSgpYcHcyQjRCT1d2S3NsUGVxa1NybEsyTTVlclEwYkszcndDUzBwTnJBN3dXL296NGFLejJ2VmFxSlRRMm16UXR5ClUrRzhXZFFNNFdBNUhSNWRpbjdKUjVGZFNCMjJlNEpxUnVVZ01IVEdOcHpqN3NaV1VhRk91QUhFQjcrME84UlcKQWxWdEVDc0JJYlhQaU13UTAwMDdiZ1F0M0h3QkxyUmxUN2xGSklyenVxbUZDU0d5SW45Tkt4TUVDeWFDZlhLVworT1gzT2xRdjk4Q2NGVVR5VkMwcXoxaE9yVGxDWXhJSFZ1Y001dUJCMkxwdmZ2THgrc2FVOGxVRHRJNTh1NXU0Ci9Nb3N3WjFFUmNXbG9HN1lDSnptNmt1VDhkZ3laUjFyTFN0QnJuTFhkVlB6MmpaWU03RkljeE8va0QycVBKRysKUTJ5MTN1Znk3RURmV1RybDhnZ2dqRjFWcWd1YWViSTdnRXhqVzBTc1NialpLa3J5S1Q5VnNwTDVOMTFSU3NmTQpMTTU0R09aUFF2VnlMR0U5TXY4S2YzUkUxWGVPVkwwREoxTzFHOUZ3QXMxbW1ob3liT2tpTVdCYkJpc205TGlCCmYwZW1XRE1DeHp2cVMzUHhLQ1ltRGtuYmVkcU9ZRW5rSVFmMnRIcE80c1JRMkU1elYva0hjREUxSUQwRXV4WW0KWDhzMU1SL2NTT0s2cnpKWStkd1hKSWtKWEJjY1prQjJuVVVJMXB5NDB0WmtXWDllNk5lTW9iUWFXTG5MRERjcgovWG9JV2JuN3VFV3paVW9uL09VbHdmVzNweXp4UmtCOU1STmNhWno5ODNTZXdqSTg0dGhNRG9EOEdZbmlKTGhTCjU3ZkFnVXZxemFDdk13blp4enJDN2RRK3RheHpvL014TERxcmlHUDRNYkZ3aTBac09XcEc5WUpoY2J6NldpTE8KT3JnVGlrUVkxQ1l3a3p5TjFnOEFMN0Vid2N3WHJ6a1hpR3E4V2x4bGMvSHllTi9STUkvWFhWeXYvU2M2ZG5BOApmK3ZLYm1xR2k3VjZDREc3QXNGUWNsY1hhWEY4enErbUZLWnJvd0ZFWlQwaitnZ09DOElwYnBNTTRKL0pacmxGCjNVT282MzcxRWJyc0FKTUhFRUJMb0NGb0pwR0VEc1pQbURvMGhBZnZKRnZ3R08vbFM2N05NOUlVcCthYUJWak8KL3NkQ3JKWlZzckpXR3ZRZTN3MlhsYlJHWXVlY2lKaHpVRWs3akcwcml0Z05DT1FzaXRlWXVvRnNTVCsvYTZ3TwpyRzBEWHQvMkVsV1pjcHcrYnFlOHdLb0VYTWlsK0hQNnpRRENKRTA1NFJMUXpVWWYxdUVEODRoQjVMa2JxbnJOCk53elV4dmVubzdqRWN5ZmwrTXlUaTZML1RNeDE3clNJSXhjTUxqSGZFOU5maElFWWFTdFVQcGxPWnptblZ3N1MKWWVBbnRNUUppb1RNZXprZzRVNm16TkhZYkU3YVg3eXdZQUV5TmpBWEJvZnlwUmJ2RThZR3cvczg1Y1ZTUjBhMAp6alhybXBlWm80RnpQU2VIU2RLcHdEdFB2eUxWUExZMlo3MnpoTTBpOWF3dHhQR2ttRkZGdUJhdUlvVC85WDhuCkE1YjlENzdFaVpqbjhwS25FWmgvRzNQUi9uSVhOZ0VHcjFKV0xqaUQzdWp0YjdGd24zL2lyY1BDZ1pQQkZsbkcKd2pLbkZSVUNDc0J0UTBGM0hHa2FubnA4SlVYWGtzUkFCdnBRVitMK3B2cE5uRXpEMXFLS3g4amU2OW45MS9mWgpmanZubjAvblVORWxDK2w4UzZzZ0JVQjkxWXcyQ3NEMGd3dHhBUWk3QVorTGZMMnl3YTV4c3lvcmhpV1pmVkVsCk9TVTVWcUlMdG1MYjVTTHRmYlJ6NkdlV2srTTVMUzcxbHNlNDFhZVBHNWNCZUIvZkNwTzRaaWEwQ1VOVFZFRlMKSUZWQlZJa0NXQVFUQVFnQVFoWWhCSm9KNEpOeWtsdmtxZUhLT2s0SlRwelIrcFNjQlFKaURNWHVBaHNEQlFrRAp3bWNBQlFzSkNBY0NBeUlDQVFZVkNna0lDd0lFRmdJREFRSWVCd0lYZ0FBS0NSQk9DVTZjMGZxVW5ISlNELzlBCndWZGJqdGJHclVQdVY3V0dzUXB3N3llVnZqZ1lzWkVKVEdFVnEzZFFaMllBblY5WlBoYVJrN3lCMGRsaUtOWEcKR09GUERiS3NaVnN6eXk1aVBRWjZ2OGRoL1B2TlFNOHc2Rit0ckxjakhTMVNGbGI0RS8zeTgydnk0dFNOVGc4QwpDMENYTG1JeEM2TER6RDhvKzVlTDBaSlJCc1JlY3RRamJDY0IyWHR0VExLM3RYaWI2VkZtSFJWMjF2QURiejExCmVmU29mazVRSWM0USt3akQxNmxTYzZGckNZWVBCdmxuYmF2ZFBEdm15SnpwU1Vxc1hnazVYREthM05iUjdNSUkKR00xTVZVNHFGdHZzODh0Z09DMDJHdks2SG1tR0RzNkJUbHkyNHJLbHVHVUJ2dEUxZW05bWZkOFpoSTBHWXQ3RQovQTFnYTRiMlFXa3B5YXNhb2h1Y1V4U0JFT1E1ZFlPK3J2YVBtQmxVRWtwb2JzcEtXaUhGWEJPNGdUbnF2Z1BVCjVUbDd0WjNyZlV4V0JEdmtjK25SMzA2aVYrNDFMQ3B3YXMxbVFMbXd5WXBrTldUREdyZzBIU2VPcE96bVpYWHIKNldWS1ViRWVtK1poSUlsNmx2Z2RiSEdqRkZXYklVSW40elNwTk1ycDh1aDAya0RBUktFdGQxZDQzb0xKWjI2QwpLNUQyOWZJVnEvdy9uZFdNcmk5SWduY2hOUFRlRFNaZGRKVFdnTUc1SEFLbWJxLzVYNE83MWdybGpoWnpLUFdSCmU4RS9abDVoc3dSb3FnY2Y1c3V3WDZ5cHRxTytzbUVVTlNWMVJYNjc4ek9WVlpYcjc2YnlkSU03NzBja0hpc3EKQk81cmF2YnJHV1ZhOUpmQ0hoY1lRYWtMNGVoMTdZRkppWEZrQkhzRmxKMEhSZ1JpRE1YdUFSQUE3cktTRGVDUQpwQm1BWmNHQXZZTVd1ZU9OUkVGUjZESUtEVjY0RWZZUmdBUHNuRUQ1bmJqcWQwbjQ1dU52OGdSUTdYbmt6a3M4Ck94Qy9tS0trQzBlSlhBZWNFZXpaeWJBcTNCZ1VTSkJJbzZjQXlqalFremY5WHdUQ0txaHdXZ1BRTzdXVlNUQk8KOWM4bldFSEM2bFB4UW9KVFZwZVhvVTBoUlNZMTlxY3BOMi83c2VRQ3UyRXZDMU1GVUJqRGEwUnQvNFU0Skh6eAo3bkc1cmgvQ0llR0VST0JKOS9ZN3hQY3Jrd25rOWRUajZCd1ZuL01EWGE4cU1yRHN1S2JTYkJ3MVVUOTNVM2poCmJDWnE2ZGxBWjAzUUZzdUltRUtKVlR5cmRpL0Fqbm9KTWt6YnVKTGVSY1NPejRmQkFYUnQ3aEVOWmt4ckJhL0oKREl0bnJxMjBUYXFQcmx6ak9GQmxOdzlXM3lzMG9UUzY4dHZBSGVxRGM2a1BTRzRhZ1o5Z3hjUnAvQ3VCbWNPSQpVYzcrdjY5Y21wMVlBZlVPSGRrN1NzNnNoVEhCM0hSeXFiblhGejl4cCtjeTZOb2ltbkpvTUdGcFpLUWQ2dzlpCnRyTVEzcmU0aWVMR1VEVVJCeHZ6eXN4ZEl1L3NXcVJhMnloSldwUVVHTndXUjdBWnM3NDhHTHFZaVhpR1kzMU0KL3ZwRU5YeklEVTZLSzhxeE01ejAyTzF4QXFySFFGRkErcWtKSmgzUlQvZEVWdjFnWS94amJGV1B1VE5EMjllSgovWnVzTlJITjY3NTVKVHJBT2g4dGhTak1SV2J0aDRCR0QvcDVTKzc1d1dSNmRTMnBlOXdSTldodlNLVFIrYjgyCldnS3Nzd3dwVnNkM0tFcDAzekVDTU03VTdPVEFXUk9RcHdzQUVRRUFBZjRIQXdJNVVKRzQxV2pGei9QVVk1cjUKOW1CcHkvUlgzbUNHMlNQc1JLUXJtb2E1aFJjQzVQc1MycXJGSFdLTUMrRXpJbWJhalhiZG1CWnlYdCtPcWpPTAo2ZVZ4WkRveWZoelBUajdWK0d3Wk45a3RUemNQVWJBak9iRU9xMGtkM3h3RFZhRldKU2tyVSsvTHh5M1ZJM1ZuCjBoUys3TUxBTnIyN1NzSjEySzFUMThNOEcxK1A1QUxoRG52Wi95TS9xc3lBazFNWFhyVnREQTRDc1JzRnd1QU4KRUpKZ0g5anJsTk4yS0h3b21GNnRjTlNmeG1jdWw0S1JFYWVGd2ZUR0lyU3hybEZsR2h1VmY4a2xkWkRhbXcwVQpic08zYm1xOXQ1NU1IdWw0WWlRb0srUlRTMG10Uk1MWExTcjRuR3pGR3ptVDRUY3NqNDJnUHc4cGZPczdIMm4vCktkNXlEVFViRFdoRGg1YUdLZStJemZ1blhxVEpkT08vWS9yajRyWThEdkN5U2NJZkJSN0NuRjJYam1vR0Y5MW4KS20xR014TGc5M1h5RjlBQzRVV3dRWUVtUVZINFYrck5KRWhPblRWTG5uKzM1ZmZoT0Q0Y0xUc0U4Uk9RaFpHOApsYkQybTltdzlHV0I5VGFUWUNGMndsMXJxUTRSeURodnBSYStiZXY5ZjI0ZmJ0cnVQOVg0ckFETExHWTdLbjVRClkzQi9BSUxqN0c1NnFtL2V6b3ZzYm9pUHNWSk5CeTYyRjBBYTE1K1RkTmRCNVI4bUFvOFU0VnM2dldYYTl2YTkKeVg1a3dqN01hb21HQzJDa0RMVkNQQWRtVEVZNUVoVlRadDQ2TTlSMnJYQWFSVFBhS0tnZDNaWTNVdStEVWFOagp2UVdJOVNUWVJqSHBEbHJsRThpb005RERLYXo5Ty9UazBJMDdYZHJpdmVSYlFud1VoYUh3SmpkSEtjd21kMzUvCkpZcDNKNys2dUpjMlZiNXI5NkNsdzdmbXRLeWMvbTJBcDRhSlJMdWl6TllMTDBvdUhtUklSWGErWHk3K014cncKSVhUeFVPQ0dsODdXNHBLYytCYk9pU1FNc3dYQitDKzV0RVVIaW5rUndXWTMwS1R2ZnNwU1laa01uMDFNMlMwZAovU3RtQnk2TjNZOFh0WVlVUEgwdzI3Nkp0MUNzNkpNUDN1Y1M4WnZWaElzenhNbFFWWCt4K01NSTY3OEdodHZuCnowcW5qKzREbDN3RUF6bUhLRjh4aVJoMjV3VGZBRXdZcUJ5bG1qSUxvWVE1NDlyclBzSW15azFzdDJxaGo4ZC8KYVlVRVN3MEdHZWRsNGtGbVNCVkg1UGMxSWlqanpqRjVESHArZVBJWXpJNzRSL3RTRzRXdituNlNUSnpsVkdqbwpRMWZ0cXRzRzZ6cHZsTjBFcE5paGMzNTA2c25yRFpDRUJ1a25QTFI0bHV4eXZUM0VRR3h1NU1COWxTbmtRSHI2Cm9lMTV3VitldzFQR05pSDRLRzNVZnIzSjVob1FLaXZIQ1Bzbnk2TmQwa1I2UjFtY1BGOEF6MTdzR1ZYbGZvWEgKUzlRMDZQWU8zQlpJZ0pOQ0NmQ2ZPeXhOQit0R1VkZEUrMzE1OURuTVBiWjY3SVdwMVppL2ZsM050UGk2a05KQQprUVpkamY5SVd5eDhMY2M0ZkVVWWdCZkpDejh2SU45ZzcyYjcxL1M0T0NzOXpVakRnTEgyY2tucGl6bFVqQ1JQCmZRZUdpcGZoVjNaY05RWFFidmlmME02SGVDcDlBWWIxYlZqNUJ3Mm80VTQ3d21PdUgyaERha3ZiUnNMTEdzdEcKc0J2LzBXVU15dWdRSHNlUVhXRkFLcjYyZU5oQmdmMFYzZDJ1SXlwbzErbGFGUGN6bHM5WFprQUFqNkIxeGtuaApwZ0NMelhHMVVQUUdlOW04Nk5aME4wWUNxckRoZzB2S0lHdXJPNEE2Q0xvb0pJN3FqSlFQdGZkTk1ZWmwrNmpRClc1S3l2ZjQ2Y1hDVkVXemFrRTVMRDZpMmYyVjBNSU9GZE9OSDdQTTZSdVR1K3cvanZxV1V2dTEzTDhhMFo2MHMKT3lqcmdlOUYrRWlPN3B2YVBNS1JsbXo0bUhRVmdHMktQeG9PQVh3UWlGNnA0Y0dtS0pNa0pjVUMzejdJWFZaeAo2TmpxajJZc1QzMXJWOGhJR0NSa3ZTbXZPSURBRGttMTVZYzg5TnZoT3ROaHVOUGZMSVM5dys2UlEzN082ZU1uCmdUYis3ajM4ZW8yWEMxNXlFY3JQVUtXQ2JjNktIZ2wySG11bjR6TGY3S1EraU1wa0puc1VVczFQMnlvY2F0ck8KemVJcFMzVkhaZ1pYY1dFMS91b1I4YVFGbHJ2UXlidVppUUk4QkJnQkNBQW1GaUVFbWduZ2szS1NXK1NwNGNvNgpUZ2xPbk5INmxKd0ZBbUlNeGU0Q0d3d0ZDUVBDWndBQUNna1FUZ2xPbk5INmxKekl3US8vWWYwckNuakxqdTJjCjl1dGpwRGxzdTNPRXdmUW9vWkxNdk1VU0lTRjM1Tkg0VHFQOGhPQWRUdUJtRWUvR1pHTnA5YUxKYVdiaGlvUC8KVnViZ3JRNEtQdFRrOFp0VHJJRmpSZWt0QTFFVUYwV3dWL1hNTDdDRWg3UjBlZE40R0dIazRDaENGaEdZZGlPWQp2VHladGdZL1NGZGFWRGhxZVUrcVNwa0g3U2ZJY1AwY2lIR0lkbnpqMmRkOE05UkVUVHNwczROcGR4Um90ZXVoCm44c254U3dqcGVuTjBhMnoxZ203V3owckVWcGJoRmZ3U0RKUHpmU3J2cHZrTlU3Zi9aUGxTMjNVTk9kNFIraGsKOGFCTTNHU0pHNkpjbjVpLzh3MlRhK3h1RlZSL2VNb1FhTE5xQi9ISnAwRStZdnlQa2d3eER6RTV2RWZoVTlmUgpuOEZvQkp6Ynd1OVN3YU4xZkZXNVNva0RYMUM1azU2a3J1WkYyaDZxWE5HNmVENzVmWkxieTd4UmM1RnR6UndjCmRxeU9hZEF5MGZLbzlCTWV4aXRhOGhpZFFTQWlUK2FrdWNEb0FvN0s1eVhHRWZFdmFLRjJiQTZORzROTDJaSnUKMURuVFhFa0kwSEtOdTNmSzBoaElVQ1BWeE9GSXlGcDI1RUhSU1ppSkp5cVVmWWlOYnhYaVNHUGRnRzBXTDJVNgpScXY4VVZEWDFiWVVSa0YrejByUUoxYmVKS1dPYXhjMS9qVy9tczdwczhDZUgxUHdxYlBjNUpBN2xCMnREdDVSCnhXalBJbytLVkdGSVF4Mkk0NUlrY0YwMHdoaXJlbTcya0RKUzlGOVBNVEdRbnVDTldNNU1HRUJGcFBTQk82VG8KVTBzb1JhaEd2bExYMXdnVHJQM3JYYnl5Y1lYckNxOD0KPUVsZTEKLS0tLS1FTkQgUEdQIFBSSVZBVEUgS0VZIEJMT0NLLS0tLS0K} # default value is just for testing purposes
  #      password: ${CSV_TRANSACTION_PRIVATE_KEY_PASS:abwcWUA8igWhzh}
  api:
    baseurl: https://${CSV_TRANSACTION_DECRYPT_HOST:internal.it}
  blobclient:
    basepath: storage
    apikey: ${INTERNAL_SERVICES_API_KEY:myapikey}
    targetContainer:
      rtd: rtd-transactions-decrypted
      ade: ade-transactions-decrypted
  splitter:
    threshold: ${SPLITTER_LINE_THRESHOLD:250000}
  enableChunkUpload: ${ENABLE_CHUNK_UPLOAD:false}
  skipChecksum: ${SKIP_CHECKSUM:false}

---
spring:
  config:
    activate:
      on-profile: test
  cloud:
    stream:
      bindings:
        blobStorageConsumer-in-0: # name must match [handler name]-in-0
          destination: rtd-platform-events
          group: rtd-decrypter-consumer-group
          content-type: application/json
          binder: kafka
      kafka:
        binder:
          auto-create-topics: false
          consumerProperties:
            key:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer

applicationinsights.enabled: false
---
spring:
  config:
    activate:
      on-profile: default
  cloud:
    stream:
      bindings:
        blobStorageConsumer-in-0: # name must match [handler name]-in-0
          destination: rtd-platform-events
          group: rtd-decrypter-consumer-group
          content-type: application/json
          binder: kafka
      kafka:
        binder:
          auto-create-topics: false
          brokers: ${KAFKA_BROKER}
          configuration:
            max.poll.interval.ms: ${CONSUMER_TIMEOUT_MS:600000} # default to 10 min
            max.poll.records: 1
            sasl:
              jaas:
                config: ${KAFKA_SASL_JAAS_CONFIG_CONSUMER_BLOB_STORAGE_EVENTS}
              mechanism: PLAIN
            security:
              protocol: SASL_SSL
          consumerProperties:
            key:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
            socket:
              connection:
                setup:
                  timeout:
                    max:
                      ms: 200000
                    ms: 100000
            request:
              timeout:
                ms: 60000
            connections:
              max:
                idle:
                  ms: 180000
            max:
              partition:
                fetch:
                  bytes: 10485760
            session:
              timeout:
                ms: 10000
            metadata:
              max:
                age:
                  ms: 180000
            # partition:
            #   assignment:
            #     strategy: org.apache.kafka.clients.consumer.RangeAssignor
