
logging:
  level:
    root: INFO

spring:
  cloud:
    stream:
      bindings:
        blobStorage-in-0: # name must match [handler name]-in-0
          destination: ${KAFKA_TOPIC_BLOB_STORAGE_EVENTS}
          group: rtd-platform-events-consumer-group
          content-type: application/json
          binder: kafka

      kafka:
        binder:
          auto-create-topics: false
          brokers: ${KAFKA_BROKER}          
          configuration:
            sasl:
              jaas:
                config: ${KAFKA_SASL_JAAS_CONFIG_CONSUMER_BLOB_STORAGE_EVENTS}
              mechanism: PLAIN
            security:
              protocol: SASL_SSL
          consumerProperties:
            socket:
              connection:
                setup:
                  timeout:
                    max:
                      ms: 200000
                    ms: 100000
            key: 
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
            request:
              timeout:
                ms: 60000
            connections:
              max:
                idle:
                  ms: 180000
            max:
              partition:
                fetch:
                  bytes: 10485760
            session:
              timeout:
                ms: 10000
            metadata:
              max:
                age:
                  ms: 180000
            # partition:
            #   assignment:
            #     strategy: org.apache.kafka.clients.consumer.RangeAssignor
